
import type { Exam } from "@/components/campus-connect/exam-form";

export const initialExams: Exam[] = [
  {
    id: "1",
    name: "Mid-Term Examination",
    class: "10-A",
    subject: "Science",
    date: "2024-09-15",
    time: "10:00 AM",
    duration: 180,
    totalScore: 100,
    status: "Upcoming",
  },
  {
    id: "2",
    name: "First Unit Test",
    class: "12-B",
    subject: "Mathematics",
    date: "2024-08-20",
    time: "09:00 AM",
    duration: 90,
    totalScore: 50,
    status: "Completed",
  },
  {
    id: "3",
    name: "Annual Examination",
    class: "11-A",
    subject: "Physics",
    date: "2025-03-10",
    time: "01:00 PM",
    duration: 180,
    totalScore: 100,
    status: "Scheduled",
  },
  {
    id: "4",
    name: "Half-Yearly Examination",
    class: "9-C",
    subject: "History",
    date: "2024-11-05",
    time: "10:00 AM",
    duration: 150,
    totalScore: 80,
    status: "Upcoming",
  },
  {
    id: "5",
    name: "Second Unit Test",
    class: "10-A",
    subject: "English",
    date: "2024-10-01",
    time: "11:00 AM",
    duration: 60,
    totalScore: 30,
    status: "Scheduled",
  },
   {
    id: "6",
    name: "Annual Examination",
    class: "Std. XII",
    subject: "Biology",
    date: "2025-03-15",
    time: "10:00 AM",
    duration: 180,
    totalScore: 70,
    status: "Scheduled",
  },
];
